### ISSUE TITLE
Wireframes for 1st Draft

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#1]
This should highlight the minimum needed for a user to participate in a local Systers event:

1. Login - Facebook, Google
- User uses a previously made account or manually signs up with an email.
2. Include Profile Screen. 
3. View Events.
- Can be displayed on a map or list. (Maybe include options for different views.)
- Include a screen that shows the event details. (On map or list style.)
4. My Schedule
- Includes events the user has registered for and events the user has registered as a volunteer for.

**Comment by MeepyMay** [comment]
- Headers = Blue/Green
- Errors = Red (Should not be used for anything other than errors.)

**Don't use secondary palette unless absolutely necessary.**

![screen shot 2017-05-11 at 16 20 05](https://cloud.githubusercontent.com/assets/2440938/25971135/3831a2ac-3669-11e7-9b91-0fd69b45719c.png)

**Comment by pandilladivya** [comment]
@MeepyMay @sandarumk @HimanshiJain 

Am I supposed to provide wireframes for only few modules which are mentioned above.. or Should I make them for the whole application?

Thanks :blush:

**Comment by MeepyMay** [comment]
@pandilladivya Mentioned above! Sorry Divya.
