### ISSUE TITLE
User logs in with Facebook Account

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#16]
## Description
_[TEMPLATE] As a (USER), I want to (DO THIS), so that I can (ACHIEVE THAT)._
As an attendee, 
I want to login with Facebook, 
so that I can include my information to register for the event.

## Mocks
![screen shot 2017-06-09 at 20 01 58](https://user-images.githubusercontent.com/2440938/26998163-900fb8f0-4d4e-11e7-9a85-db83bc28b05d.png)

## Acceptance Criteria
- User logins to Facebook.
- User can review information provided.
- User receives success/failure integration message.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 2 Hours

**Comment by pandilladivya** [comment]
The modified version of the mock 

<img width="322" alt="screen shot 2017-06-13 at 9 03 36 pm" src="https://user-images.githubusercontent.com/16818129/27090900-2483616e-507c-11e7-9ff2-896b33afbd71.png">

**Comment by pandilladivya** [comment]
Closing this issue.
Merged via #3
