### ISSUE TITLE
User logs in with email.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#18]
## Description
As an attendee, 
I want to login with my email, 
so that I can include my information to register for the event.

## Mocks
![screen shot 2017-06-09 at 20 01 58](https://user-images.githubusercontent.com/2440938/26998163-900fb8f0-4d4e-11e7-9a85-db83bc28b05d.png)

## Acceptance Criteria
- User logs in with an email.
- User can review information provided.
- User receives success/failure integration message.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 2 Hours

**Comment by pandilladivya** [comment]
The following is the modified mock.

<img width="322" alt="screen shot 2017-06-13 at 9 03 36 pm" src="https://user-images.githubusercontent.com/16818129/27091021-86ba9604-507c-11e7-9219-782ea3eff5bb.png">

**Comment by pandilladivya** [comment]
Closing this issue since it has been merged. 🙂
