### ISSUE TITLE
User registers for an event.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#19]
## Description
As an attendee, 
I want to register for the event
so that I can obtain information about the event.

## Mocks
TBD @pandilladivya Can you include a mock screen below?

## Acceptance Criteria
- User information is relayed to the server via Etouches API
- User can review information provided.
- User receives success/failure integration message.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 5 Hours

**Comment by pandilladivya** [comment]
Closing this issue - Merged via #71
