### ISSUE TITLE
User views available events close to their area.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#20]
## Description
As an attendee,
I want to view the events in my area,
so that I can obtain information about the various speakers, content, venue and timings.

## Mocks
TBD @pandilladivya Can you include a mock screen below?

## Acceptance Criteria
- User is able to view events on a map.
- Summary of the event is visible on a small popup when clicked (Name, Time, Venue).
- Successful integration with etouches events on map.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 5 Hours

**Comment by pandilladivya** [comment]
Map View
-
<img width="331" alt="screen shot 2017-06-13 at 9 26 26 pm" src="https://user-images.githubusercontent.com/16818129/27092497-396ae46c-5081-11e7-80d5-ea8deaea00e1.png">

On Info Button Click in the action bar
-
<img width="331" alt="screen shot 2017-06-13 at 9 29 03 pm" src="https://user-images.githubusercontent.com/16818129/27092543-58dfceac-5081-11e7-992b-97f4a6a55082.png">

List View
-
<img width="314" alt="screen shot 2017-06-13 at 9 52 12 pm" src="https://user-images.githubusercontent.com/16818129/27092944-ab5649da-5082-11e7-8357-d8780455b688.png">

**Comment by pandilladivya** [comment]
This is done via #69 and #64

**Comment by pandilladivya** [comment]
Can we close this @HimanshiJain @sandarumk ?
