### ISSUE TITLE
User filters events to see where they volunteered.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#21]
## Description
As an attendee,
I want to view the events I have signed up as a Volunteer,
so that I can plan accordingly and review responsibilities before the event.

## Mocks
TBD @pandilladivya Can you include a mock screen below?

## Acceptance Criteria
- User is able to view volunteer status on small popup of events on the map. 
- On the detailed events screen, they see volunteer status.
- User can filter the map to show only events they registered for as volunteers.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 8 Hours

**Comment by pandilladivya** [comment]
Merged via #72
