### ISSUE TITLE
Users can view their location on the map.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#23]
## Description
As an attendee,
I want to see where I am in respect to nearby events,
so that I can plan accordingly in regards to transportation, etc. 

## Mocks
TBD @pandilladivya Can you include a mock screen below?

## Acceptance Criteria
- User can view their location on the map with nearby events.
- User can view nearby events when traveling to new cities/countries. (Updates with their travel.)

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Able to show feature in demo.

## Estimation
- 4 Hours

**Comment by sandarumk** [comment]
@pandilladivya This is finished right?

**Comment by pandilladivya** [comment]
Currently we are showing all the events. Not based on location wise.

**Comment by sandarumk** [comment]
@pandilladivya What is the final status of this? Please mention what is available and what is not so we can close this and have a separate issue for the ones which are not available.

**Comment by pandilladivya** [comment]
@sandarumk This is done - user can now view their location on the map.

Fixed by #81
