### ISSUE TITLE
Validate form inputs for SignInActivity

### ISSUE THREAD

**Issue by HimanshiJain** [systers/volunteers-android#29]
Validate input fields before making calls for authentication to ensure application security and to get the right data.

**Comment by sandarumk** [comment]
@pandilladivya When you are sending a pull request, please add the issue number as well so it will link the issue. It will be easier for us to close the issue along with the pull request

**Comment by pandilladivya** [comment]
@sandarumk Okay.

**Comment by pandilladivya** [comment]
Closing this PR since it is merged via https://github.com/systers/volunteers-android/pull/30
