### ISSUE TITLE
Mentors create issues for the first version of Volunteers Android.

### ISSUE THREAD

**Issue by MeepyMay** [systers/volunteers-android#4]
## Description
As an Student, 
I want to view all the work I need to do, 
so that I can manage my time and program with weekly deployments on time.

## Mocks
N/A

## Acceptance Criteria
- Student can view all user stories in the issues list.
- User stories follow this format.
- Includes **labels, assignees, and added to the "Student Tasks" Project board.**

## Definition of Done
- Matches all the user stories discussed in [VOLA 1.0 Doc](https://docs.google.com/document/d/1Rr-VI1J54lATCDA0Vl7pvSVrJI7br8xmudMHuEU3DPY/edit?usp=sharing).

## Estimation
- 1 Hour

**Comment by MeepyMay** [comment]
@sandarumk @HimanshiJain I helped @pandilladivya by creating the issues. Please view and review them as I don't have a good idea of time estimation. Thank you!

**Comment by sandarumk** [comment]
Sure. Thank you very much @MeepyMay
