### ISSUE TITLE
Integrate Travis

### ISSUE THREAD

**Issue by sandarumk** [systers/volunteers-android#47]

**Comment by zarka** [comment]
@sandarumk Can I work on this issue.

**Comment by sandarumk** [comment]
yes go ahead

**Comment by zarka** [comment]
@sandarumk 
I have added travis to the project. But the build is failing because of lint found some errors.

We have two options - 
1. Ignore the lint check in travis.
2. Adding the travis and then fixing the lint issues. (Preferred)

How should I proceed?

**Comment by zarka** [comment]
@sandarumk @HimanshiJain @pandilladivya
I have added travis to the project. But the build is failing because lint found some errors.

We have two options -

Ignore the lint check in travis.
Adding the travis and then fixing the lint issues. (Preferred)
How should I proceed?

**Comment by sandarumk** [comment]
My suggestion is to remove the lint check from Travis. @HimanshiJain , @pandilladivya I would like to hear your ideas as well.

**Comment by pandilladivya** [comment]
Yeah, That can be done and we can create a separate issue which includes all lint errors like removing unused code etc, So that beginners can work on them 😊

**Comment by zarka** [comment]
@sandarumk @pandilladivya 
I would recommend - Adding the travis and then fixing the lint issues.
This will help us maintain the code quality.

Rest is up to you, I will proceed as directed.

**Comment by HimanshiJain** [comment]
@zarka can you please elaborate in detail the pros and cons of both the approaches and possibly some links that make you think the above option is better?

**Comment by zarka** [comment]
@HimanshiJain 
## Enabling travis and then fixing the lint issues - 
#### Pros
1. We will be able to keep track and fix the lint issues in the codebase.
2. We will be able to check the quality of incoming code (PRs made by contributors).
#### Cons
1. Travis build will take around 10 - 20 extra seconds to complete.

## Ignore the lint check in travis - 
#### Pros
1. Travis build will be slightly fast.
#### Cons
1. To disable lint check in travis we will have to disable it in the `build.gradle` file. This will also disable the lint check locally. Hence the project will have a lot of lint issues.

I suggest going will the first option because it is important to maintain code quality of the project. Compromising with code quality for 20 seconds of extra build time doesn't make sense.

**Comment by sandarumk** [comment]
It is not the extra build time that I worried about. As this is an open source project, and a fairly a new one at that, we will be getting a lot of new contributors (specially in GCI and GSoC). Having a failing travis build in their PRs will not work as an encouragement. 
What we usually do for the lint issues in other projects is make a separate issue with lint list exported and let the new comers fix them as beginner friendly issues. This will attract a lot of new comers as per my experience with the previous projects. Since the lint issues are fixed in anyway, this will not also act as compromising code quality.

**Comment by vaibhavsingh97** [comment]
@sandarumk I have one solution for this. Please visit [Hound CI](https://houndci.com/).
@zarka If we use Hound CI then we can go with second option

**Comment by sandarumk** [comment]
I think for now 
```
lintOptions {
        abortOnError false
 }
```
would be sufficient. But @vaibhavsingh97 if you can do an analysis on Hound CI vs Travis and what will Hound CI do better than travis, and paste here that would be great.

**Comment by zarka** [comment]
@vaibhavsingh97 
I was going through the HoundCI docs. It dosent support java language.
Instead we can use [codacy](https://www.codacy.com/).

**Comment by zarka** [comment]
@sandarumk 
I don't think Hound CI build your code it just checks the code quality. Also it no where on the website it is mentioned they support java.

**Comment by sandarumk** [comment]
We were planning to integrate codecy after travis. It is good that it came out.

**Comment by zarka** [comment]
Should I proceed then?

**Comment by sandarumk** [comment]
Yes. Sure. I will open up an issue for lint

**Comment by zarka** [comment]
Will send a PR now.

**Comment by sandarumk** [comment]
Great!

**Comment by vaibhavsingh97** [comment]
@sandarumk Sorry! Hound CI don't support Java as of now. @zarka Thanks for correcting me.
Yeah! Codacy is a good option

**Comment by zarka** [comment]
@vaibhavsingh97 
Happy to help.
