### ISSUE TITLE
Create a release for the 1.0

### ISSUE THREAD

**Issue by sandarumk** [systers/volunteers-android#54]
**Description**
As a user, I should be able to get the source code for 1.0 release

**Acceptance Criteria**
The release should have the source code/apk (if possible) and the git tag to the said branch.

**Definition of done**
When the user click the releases tab in Github, it should list the release 1.0

**Estimation**
0.5 hours

**Comment by sandarumk** [comment]
https://help.github.com/articles/creating-releases/

**Comment by sandarumk** [comment]
Should be done after #34 is merged.

**Comment by pandilladivya** [comment]
@sandarumk @HimanshiJain 
https://github.com/systers/volunteers-android/releases/tag/v1.0

Created a release for v1.0
