### ISSUE TITLE
Fix Lint Errors

### ISSUE THREAD

**Issue by sandarumk** [systers/volunteers-android#83]
This issue is to track the lint issues in the project and solve them. If you are going to fix a lint issue please mention as a comment about what lint issue you are working on. If the existing exported list is outdated, you can first add a new exported list and choose an issue. It is recommended that you do not pick more than two lint issues because we need to keep them if possible for the new contributors.

**Comment by sandarumk** [comment]
@pandilladivya Can you add the current lint issue list exported so that others can get an idea.

**Comment by vaibhavsingh97** [comment]
@sandarumk instead of `Status: Available` we should use `Beginner Friendly` (Green Color). Just small suggestion

**Comment by zarka** [comment]
Running `app:lintVitalRelease` gives 9 errors.
These errors are about permissions not being direct child of `manifest` tag in `manifest.xml`

**Comment by sandarumk** [comment]
You can export the lint list similar to this http://chamika.github.io/PCSA-Issues/ and paste the link here so it will be easier for the new comers to come and pick an issue

**Comment by pandilladivya** [comment]
Here is the list of lint errors in the project.
https://pandilladivya.github.io/vola_lint/index.html

**Comment by BaaniLeen** [comment]
Hey @sandarumk @pandilladivya 

Can I solve the following 2 lint issues  : 

i) Incorrect order of elements in manifest isnpection.
ii) Menu namespace inspection error
as mentioned in the list of lint errors in the project.

Many Thanks! :)

**Comment by pandilladivya** [comment]
@BaaniLeen Since this issue is for beginners, you can claim one issue, @sandarumk What do you suggest?

**Comment by BaaniLeen** [comment]
@pandilladivya As u suggest.

I can make a PR for any of the lint issues suggested above, having already solved them on my computer.

Let me know which one shall I solve. Many Thanks! :)

**Comment by sandarumk** [comment]
@pandilladivya correct. You can make a PR for any issue you like. But please mention here the issue you solve so that others would not get it.

**Comment by BaaniLeen** [comment]
@sandarumk @pandilladivya I have made a PR #85 for resolving the Menu namespace inspection error. Kindly review.
Many Thanks! :)

**Comment by haroonshah2764** [comment]
@roopalJazz @niksj i have fixed this issue, this can be closed now.
