### ISSUE TITLE
Update PrefManager.java

### ISSUE THREAD

**Issue by m-murad** [systers/volunteers-android#92]
## Description
`PrefManager.java` in this project is an abstraction layer on the Android's `SharedPreferences API`. The abstraction has been poorly implemented.

- `apply()` or `commit()` is not being called immediately after `edit()`
- Preference name is set to "`LoginPrefs`", while the preferences should be for the whole app.
- Instead of `commit()`, `apply()` should be called while closing the SharefPreferences Editor.

### Update [Required]
- [ ] close the prefrences editor immediately after writing the prefrence
- [ ] Update the preference name
- [ ] use `apply()`instead of `commit()` to save preferences

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by DipanshKhandelwal** [comment]
Is anyone working on it? If not I want to help. :smile:

**Comment by m-murad** [comment]
This issue hasn't be assigned to any one.
Go right ahead and send a PR.

Make sure you read the contribution guidelines

**Comment by haroonshah2764** [comment]
@roopalJazz @niksj i have fixed this issue, this can be closed now.
