### ISSUE TITLE
Use Serializable annotation instead of interface in Event model.

### ISSUE THREAD

**Issue by m-murad** [systers/volunteers-android#93]
## Description
The `Event` POJO class is implementing the Serializable interface for serialization/deserialization. But this method has a huge overhead which cannot be ignored. Instead, use the @Serializable annotation to do the serialization/deserialization.

### Update [Required]
- [ ] Use @Serializable annotation for serialization/deserialization of `Events.java` POJO.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by haroonshah2764** [comment]
@roopalJazz @niksj i have fixed this issue, this can be closed now.
