### ISSUE TITLE
Update gradle configrations.

### ISSUE THREAD

**Issue by m-murad** [systers/volunteers-android#94]
## Description
The project is using `gradle-4.1` in which configurations like `compile`, `testCompile` etc have been deprecated. Remove these deprecated configurations and replace them with new configurations. You can read more about the migration [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html).

### Update [Required]
- [ ] Update deprecated configrations

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by haroonshah2764** [comment]
@roopalJazz @niksj i have fixed this issue, this can be closed now.
