### ISSUE TITLE
Make checkConnectivity method static

### ISSUE THREAD

**Issue by haroonshah2764** [systers/volunteers-android#96]
## Description
As a developer,
I notice that checkConnectivity() method has been declared inside an Activity class. This should be a static util method
We should make it a static mentode so that it can be used everywhere without creating new objects and incurring significant memory overhead.

### Update [Required]
- [ ] checkConnectivity should be make static.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by haroonshah2764** [comment]
can I fix this issue

**Comment by roopalJazz** [comment]
@m-murad  why this issue was reopened?
