### ISSUE TITLE
Update app to follow Google Material Design

### ISSUE THREAD

**Issue by DipanshKhandelwal** [systers/volunteers-android#97]
## Description
Update apps to follow Google Material Design

### Enhancement to Update [Optional]
- [ ] UI upgrade

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Approximately 1-2 weeks

**Comment by Rimjhim28** [comment]
@DipanshKhandelwal Though the title does not look enough but some discussion on material design is already done on #88

**Comment by DipanshKhandelwal** [comment]
@Rimjhim28 #88 Though discussions are there about Material Design but the issue is about having the correct layout in different sizes. Other than the layouts for different sizes, there are other things that we need to consider, that's why opened a separate issue for the same.

**Comment by prachi1210** [comment]
Closing this issue for breakdown into further issues
