### ISSUE TITLE
Add screenshots to Readme

### ISSUE THREAD

**Issue by Rimjhim28** [systers/volunteers-android#98]
## Description
As a contributor,
I need add screenshots to the readme,
so that any new contributor could easily get familiarised with the project.

## Mocks
Not applicable

### Update [Required]
- [ ] Add screenshots of all major activities

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**I would like to work on the issue**

**Comment by m-murad** [comment]
@Rimjhim28 
please send a PR

**Comment by m-murad** [comment]
fixed in #100
